### ISSUE TITLE
Invalid Channel ID

### ISSUE THREAD

**Issue by littlepig69** [BridgeSenseDev/Dank-Memer-Grinder#123]
**Describe the bug**
i don't know if this is a bug, but it seems that i always get an invalid channel id whenever i put on the channel id, i did everything as instructed.

**Screenshots**
![Screen Shot 2023-05-05 at 9 52 09 PM](https://user-images.githubusercontent.com/132685767/236492776-028645f8-c152-4714-a8a8-9adc071d75e0.png)

**OS:**
MacOS

**Comment by red78massive1573** [comment]
have you double checked the channel id? maybe the channel has been deleted.

**Comment by littlepig69** [comment]
i have, i even made a new server and invited dank memer into it, it still shows invalid channel

**Comment by red78massive1573** [comment]
what version is this?

**Comment by littlepig69** [comment]
Release v1.5.2, however i installed it using the linux one, i haven't tried using darwin, does it make any difference?

**Comment by red78massive1573** [comment]
i dont use mac os. but 1 thing that i know is that you should use version 1.5.0
explanation is in #91 and #98

**Comment by littlepig69** [comment]
alright, ill try it tomorrow, thank you !

**Comment by red78massive1573** [comment]
your welcome.
I suggest you change to 1.5.0 because, currently version 1.5.2 has a lot of problems.
that includes captcha not working that may lead to bot ban.

**Comment by littlepig69** [comment]
alright, i'll try it tomorrow, ill keep you updated it if it still shows the same problem, i hope not though, thanks once again :)

**Comment by red78massive1573** [comment]
no problem!

**Comment by littlepig69** [comment]
uh, i did everything as instructed, as for the using version 1.5.0, everything works without gui so i had to change it from the config.yml with text editor and put in what needs to be activated and such things as well as my token and channel id, but it still uses the old command which uses " pls " instead of / commands, and i tried using v 1.5.1 the same problem occurs with invalid channel id as well as version 1.5.2.

**Comment by BridgeSenseDev** [comment]
> uh, i did everything as instructed, as for the using version 1.5.0, everything works without gui so i had to change it from the config.yml with text editor and put in what needs to be activated and such things as well as my token and channel id, but it still uses the old command which uses " pls " instead of / commands, and i tried using v 1.5.1 the same problem occurs with invalid channel id as well as version 1.5.2.

There is no code in any version that has ever been released that does pls, so you probably downloaded something else. If you are on macos you need to use the darwin instead of linux

**Comment by littlepig69** [comment]
![Screen Shot 2023-05-06 at 8 02 50 PM](https://user-images.githubusercontent.com/132685767/236625897-cc6f6616-9d86-4fc8-9896-52f4a2f0a7f2.png)
is there anything wrong with this? if there is, is there any way on how to fix it?

**Comment by red78massive1573** [comment]
> ![Screen Shot 2023-05-06 at 8 02 50 PM](https://user-images.githubusercontent.com/132685767/236625897-cc6f6616-9d86-4fc8-9896-52f4a2f0a7f2.png) is there anything wrong with this? if there is, is there any way on how to fix it?

you should try deleting all the program files (the executable file and config file), then redownloading v 1.5.0 again.
that error was caused by you downgrading from v 1.5.2 to v 1.5.0 but not deleting all the files.

**Comment by littlepig69** [comment]
ALRIGHT, THANK YOU!!

**Comment by littlepig69** [comment]
still doesn't work, i deleted everything then downloaded it again, idk what's the problem here :(

**Comment by red78massive1573** [comment]
> still doesn't work, i deleted everything then downloaded it again, idk what's the problem here :(

is the error the same?

**Comment by littlepig69** [comment]
alright wait

**Comment by littlepig69** [comment]
i can't send my config file since it doesn't support that type of file, my file name is config.json

**Comment by red78massive1573** [comment]
> i can't send my config file since it doesn't support that type of file, my file name is config.json

you can attach a file by drag & dropping or copy pasting them to the comment section as stated by github.
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/87458936/11a27cb1-37f3-49c8-bc79-3f9eaab04594)

to erase your token from the config file, you can do it from the program.

**Comment by littlepig69** [comment]
i did, it said github doesn't support that type of file

**Comment by red78massive1573** [comment]
> alright wait

btw is the error the same?

**Comment by littlepig69** [comment]
yes, its still the same, it has no attiribute "ammo_checkbox"
