### ISSUE TITLE
program is clearing discord custom status on start

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#124]
when i opened the program, the program will always clear my status. this is very important to me and maybe to some people, because some dank servers have status requirements on giveaways or heists. It's very painful to keep on re-adding custom status every time i started the program. 

Links that could help:
https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=custom#discord.CustomActivity
https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.LegacyUserSettings.custom_activity
https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.UserSettings.custom_activity

**Comment by BridgeSenseDev** [comment]
> when i opened the program, the program will always clear my status. this is very important to me and maybe to some people, because some dank servers have status requirements on giveaways or heists. It's very painful to keep on re-adding custom status every time i started the program.
> 
> Links that could help: https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=custom#discord.CustomActivity https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.LegacyUserSettings.custom_activity https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.UserSettings.custom_activity

Turn off appear offline in settings for now

**Comment by red78massive1573** [comment]
> > when i opened the program, the program will always clear my status. this is very important to me and maybe to some people, because some dank servers have status requirements on giveaways or heists. It's very painful to keep on re-adding custom status every time i started the program.
> > Links that could help: https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=custom#discord.CustomActivity https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.LegacyUserSettings.custom_activity https://discordpy-self.readthedocs.io/en/latest/api.html?highlight=activity#discord.UserSettings.custom_activity
> 
> Turn off appear offline in settings for now

when i opened this issue, the program removes discord custom status. its not about the appear offline.

**Comment by BridgeSenseDev** [comment]
Fixed in 476c1b063577793dd31856420923bf92e9389881
