### ISSUE TITLE
program unable to complete captchas

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#127]
**Describe the bug**
When an captcha appear, the program isn't able to complete it. it doesn't click the wrong button, it just ignores it. v 1.5.0

**Error**
```
‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "discord\client.py", line 417, in _run_event
‎‎  File "C:\Users\owenh\AppData\Local\Temp\_MEI57242\cogs\captcha.py", line 21, in on_message
    captcha = embed.image.url
              ^^^^^^^^^^^
‎‎AttributeError: 'dict' object has no attribute 'image'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/87458936/236723901-8d920a5f-bb80-49ca-8382-7e8b60330091.png)

**OS:**
Windows

**Comment by red78massive1573** [comment]
btw, I think you should add a version field to the bug issue template. to make debugging easier without asking follow up questions.

**Comment by red78massive1573** [comment]
![image](https://user-images.githubusercontent.com/87458936/237015991-fb10dd75-04da-4dd2-a5c7-638f80892f0e.png)
closed dank grinder out of panic, so i don't have error code

**Comment by red78massive1573** [comment]
![image](https://user-images.githubusercontent.com/87458936/237016208-1008baec-ae83-4fc6-962b-8b35d2895b5a.png)
closed dank grinder out of panic, so i don't have the error code

**Comment by red78massive1573** [comment]
btw make a log file when closing app or when there is an error, so people doesn't have to reproduce to get the error

**Comment by red78massive1573** [comment]
v 1.5.0 - 1.5.2 is not safe for now (unable to solve captchas). DO NOT USE IT.
**Haven't tried version below 1.5.0**
**USE AT YOUR OWN RISK**

**Comment by BridgeSenseDev** [comment]
Fixed in latest pre release
