### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by tetizz** [BridgeSenseDev/Dank-Memer-Grinder#133]
wsg gang uh i don't got a bug frfr bridgy uh ima be real u can add like 4 cmds infact i did it for you gibe me like 20ish minutes

**Comment by Kathund** [comment]
@tetizz care to explain more?
@BridgeSenseDev close this?

**Comment by red78massive1573** [comment]
not to be rude, but if you want to give suggestions and an example, you should make it more clear. like telling what it does.
and this has been more than 20ish minutes.

**Comment by Kathund** [comment]
> not to be rude, but if you want to give suggestions, you should make it more clear. like telling what it does and giving other info.
> and this has been more than 20ish minutes.

Id say we just close it

**Comment by Kathund** [comment]
> > > not to be rude, but if you want to give suggestions, you should make it more clear. like telling what it does and giving other info.
> > > and this has been more than 20ish minutes.
> > 
> > 
> > Id say we just close it
> 
> the problem is we can't. we need bridgesense

@BridgeSenseDev
