### ISSUE TITLE
Captacha.py doesn't even works

### ISSUE THREAD

**Issue by chaijack123gt** [BridgeSenseDev/Dank-Memer-Grinder#135]
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/95576436/3ddec0ed-5b4f-4a5b-8b85-17fb14a1cbfe)

**Comment by chaijack123gt** [comment]
no errors showed at home

**Comment by RajSanjel** [comment]
I think problem with v1.5.2 use 1.5.0

**Comment by red78massive1573** [comment]
> I think problem with v1.5.2 use 1.5.0

v1.5.0 also problematic.

**Comment by RajSanjel** [comment]
> > I think problem with v1.5.2 use 1.5.0
> 
> v1.5.0 also problematic.

then which one would work

**Comment by red78massive1573** [comment]
> > > I think problem with v1.5.2 use 1.5.0
> > 
> > 
> > v1.5.0 also problematic.
> 
> then which one would work

i don't really know at the moment. bridge sense is also having exams. so we need to wait for any updates.
