### ISSUE TITLE
I dont know what to do 😭  pls help

### ISSUE THREAD

**Issue by AnomalyJx** [BridgeSenseDev/Dank-Memer-Grinder#137]
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by red78massive1573** [comment]
> qt.qpa.xcb: could not connect to display :0 qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted (core dumped)

can i know your os, program version and explain what you did until that happened.

**Comment by AnomalyJx** [comment]
chrome os, python 3.10.11, i did the commands from the Readme everything installed well, but when i wanted to run the code, i got this error.

**Comment by Kathund** [comment]
Chrome os its fully supported but it is still possible to run using the uncompiled code.

Stepts to download and run (done on windows but should work on any os)

## Installing Python
I couldn't find a donwload on the python website for chrome os BUT from a bit of googling and reading different blog posts I think this is the best [guide to installing python on chrome os ](https://codeinstitute.net/global/blog/python-on-a-chromebook/) that I could find.

## Installing the bot
### 1 - Downloading
Head over to the github page and download the zip
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/55346310/9a3f06da-d971-4c02-bb03-31f604202a18)

### 2 - Extracting the zip
Head over to the downloads or were you saved the file
**This is where it can get different based on the os your running**
For me on windows **Right click** on it and then select **Extract All**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/55346310/28db748d-fcce-4df8-904d-fcd9c5a74d92)
Then select Extract
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/55346310/1c25d410-312a-460e-8fac-e87c19ff64a6)

### 3 - Installing Packages
Open the extracted folder in your preferred terminal and run **pip install -r requirements.txt**
![image](https://github.com/BridgeSensepyDev/Dank-Memer-Grinder/assets/55346310/dbf60def-9645-47d5-b988-f7ec4197ad3e)

### 4 - Running the bot
Once the packages have installed it should let you type again. When this happeneds you can then run the next command to launch the program. Enter **python main.py** into your terminal. If Everything workes correctly you should see a gui looking like the one on the homepage pop up.
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/55346310/c9b84976-4cbe-4478-87f9-46a197108e04)


I hope this all help
