### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RajSanjel** [BridgeSenseDev/Dank-Memer-Grinder#145]
‎Unhandled exception in internal background task 'commands'.‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\tasks\__init__.py", line 241, in _loop
    await self.coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\commands.py", line 45, in commands
    await self.bot.send(self.bot.commands_dict[command])
‎‎  File "D:\file\Dank\main.py", line 267, in send
    async for cmd in channel.slash_commands(query=command_name, limit=None):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\abc.py", line 236, in _handle_commands
    data = await endpoint(
           ^^^^^^^^^^^^^^^
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 590, in request
    raise DiscordServerError(response, data)
‎‎discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>503 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The service you requested is not available at this time.<p>Service error -27.</h2>
<h2></h2>
<script>(function(){var js = "window['__CF$cv$params']={r:'7d0c94c5ecf28e56',m:'MPRudCDKyhbZEdax1aR4frrs_O.C_QGyKSnsJ.o5J5c-1685676243-0-AQYvsKzPGeyN2jnw5pNz4oRiqkvFoRN8Q68dNceX2QL7',u:'/cdn-cgi/challenge-platform/h/g'};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/invisible.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>

‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\trivia.py", line 36, in on_message
    category = embed["fields"][1]["value"]
               ~~~~~^^^^^^^^^^
‎‎KeyError: 'fields'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\hl.py", line 16, in on_message
    num = int((re.search("\*\*(.*?)\*\*", embed["description"]).group(1)).title())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
‎‎ValueError: invalid literal for int() with base 10: '20 Seconds'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\trivia.py", line 36, in on_message
    category = embed["fields"][1]["value"]
               ~~~~~^^^^^^^^^^
‎‎KeyError: 'fields'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\trivia.py", line 36, in on_message
    category = embed["fields"][1]["value"]
               ~~~~~^^^^^^^^^^
‎‎KeyError: 'fields'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\pm.py", line 16, in on_message
    await self.bot.select(message, 0, 0, random.randint(0, 3))
‎‎  File "D:\file\Dank\main.py", line 258, in select
    select_menu = message.components[component].children[children]
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
‎‎IndexError: list index out of range
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\trivia.py", line 36, in on_message
    category = embed["fields"][1]["value"]
               ~~~~~^^^^^^^^^^
‎‎KeyError: 'fields'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\stream.py", line 34, in on_message
    await self.bot.select(message, 0, 0, random.randint(0, 24))
‎‎  File "D:\file\Dank\main.py", line 259, in select
    await select_menu.choose(select_menu.options[option])
          ^^^^^^^^^^^^^^^^^^
‎‎AttributeError: 'Button' object has no attribute 'choose'
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 480, in _run_event
    await coro(*args, **kwargs)
‎‎  File "D:\file\Dank\cogs\captcha.py", line 17, in on_message
    embed = message.embeds[0].to_dict()
            ~~~~~~~~~~~~~~^^^
‎‎IndexError: list index out of range

**Comment by AnomalyJx** [comment]
what version of the program are you using?

**Comment by ineeddankselfbots** [comment]
same the commands stop after a certain period but it keeps using items

**Comment by red78massive1573** [comment]
this is the same issue of #98
