### ISSUE TITLE
This interaction is no longer valid, please try again, forever

### ISSUE THREAD

**Issue by ewesley2** [BridgeSenseDev/Dank-Memer-Grinder#146]
**Describe the bug**
a private message. it just goes on forever... i'm not sure if it interferes with the command flow
p.s. the automation drastically slows down overtime at the same time this: ![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/109018023/7b8aac86-97fb-485e-9c6b-b33ce9ecdcc7) happens more frequently

**Error**
not displayed.

**Screenshots**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/109018023/d355fa6d-682b-4880-80b5-e08ce820d7ad)

**Reproduction**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/109018023/5e140600-cd91-4541-87cb-13cf985f7843)

**OS:**
Windows

**Version**
1.6.0 pre release

**Comment by BridgeSenseDev** [comment]
Should be fixed with the new autobuy
