### ISSUE TITLE
Application Not Working

### ISSUE THREAD

**Issue by Coder321P** [BridgeSenseDev/Dank-Memer-Grinder#147]
Im on a windows 10 and i have absolutely no idea what the problem is because of which the script isn't working. I have attached a screenshot of the problem im getting.

![1](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/108922290/c235514e-e9fb-4d6c-917c-52fb08374b46)

**Comment by Coder321P** [comment]
btw i downloaded it from here 

https://we.tl/t-ocUZlT1Qsg

**Comment by BridgeSenseDev** [comment]
> Im on a windows 10 and i have absolutely no idea what the problem is because of which the script isn't working. I have attached a screenshot of the problem im getting.
> 
> ![1](https://user-images.githubusercontent.com/108922290/243087044-c235514e-e9fb-4d6c-917c-52fb08374b46.PNG)

Can you open https://raw.githubusercontent.com/BridgeSenseDev/Dank-Memer-Grinder/main/resources/version.txt on your browser? Also download the latest pre release from https://github.com/BridgeSenseDev/Dank-Memer-Grinder/releases/tag/v1.6.0-pre1 instead

**Comment by Coder321P** [comment]
thats the problem https://raw.githubusercontent.com/BridgeSenseDev/Dank-Memer-Grinder/main/resources/version.txt doesnt respond in time. And yes, i have now downloaded the latest version

**Comment by Coder321P** [comment]
> 

Can u help me know what changes I should make so that the application is able to access It?

**Comment by BridgeSenseDev** [comment]
It will not depend on raw.githubusercontent.com next release anymore
