### ISSUE TITLE
I can't seem to open it

### ISSUE THREAD

**Issue by Rajendradk12Roblox** [BridgeSenseDev/Dank-Memer-Grinder#15]
After downloading and editing the config, i tried to open dank grinder, but uhh it's a document with just texts from random symbols and i can't seem to find the actual dank memer grinder (i am on mac)

**Comment by BridgeSenseDev** [comment]
Open terminal and navigate to the folder the program and config is in, then type `./Dank\ Memer\ Grinder` to start it
