### ISSUE TITLE
No auto buy

### ISSUE THREAD

**Issue by JustJake2007** [BridgeSenseDev/Dank-Memer-Grinder#159]
I didn't do anything special, it just doesn't buy lifesavers or anything even though the setting is on. It's just not trying too, I see a fix for it in github but don't know how to implement it

I am on Windows 10

**Comment by JustJake2007** [comment]
Ok so turning it on and off made it so when I die with less it withdraws the money for it and doesn't buy it

**Comment by JustJake2007** [comment]
New version that says it fixes it, still doing the same thing

**Comment by BridgeSenseDev** [comment]
Wait for the next release, its only supposed to listen for when you die to then buy lifesavers
