### ISSUE TITLE
Error Running the File

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [BridgeSenseDev/Dank-Memer-Grinder#16]
I use Pop!_OS 22.04 and when I try to run the cmd ./Dank\ Memer\ Grinder, the following error occurs

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

please help me resolve this issue

**Comment by BridgeSenseDev** [comment]
Install libxcb-xinerama0 by doing `sudo apt-get install libxcb-xinerama0`
