### ISSUE TITLE
Error with code when running with Python

### ISSUE THREAD

**Issue by Cosmoverz** [BridgeSenseDev/Dank-Memer-Grinder#168]
**Describe the bug**
The app doesn't run after I enter my token and channel id. I know that these token and channel id work because last month it used to work but now it doesn't anymore. This issue happens in both current and preview. For for some reason, it works when I downloaded the windows file and it ran just fine.

**Error**
‎Exception in thread ‎Thread-1 (between_callback)‎:
‎Traceback (most recent call last):
‎  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
‎    ‎self.run()‎
‎  File "/usr/local/lib/python3.10/threading.py", line 953, in run
‎    ‎self._target(*self._args, **self._kwargs)‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 729, in between_callback
‎    ‎loop.run_until_complete(start_bot(token, account_id))‎
‎  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
‎    ‎return future.result()‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 390, in start_bot
‎    ‎await MyClient().start(token)‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 223, in __init__
‎    ‎super().__init__(command_prefix="-", self_bot=True)‎
‎TypeError‎: ‎BotBase.__init__() missing 1 required keyword-only argument: 'intents'‎
‎Exception in threading.excepthook:‎
‎Exception ignored in thread started by‎: ‎<bound method Thread._bootstrap of <Thread(Thread-1 (between_callback), started 140123425462016)>>‎
‎Traceback (most recent call last):
‎  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
‎    ‎self._bootstrap_inner()‎
‎  File "/usr/local/lib/python3.10/threading.py", line 1018, in _bootstrap_inner
‎    ‎self._invoke_excepthook(self)‎
‎  File "/usr/local/lib/python3.10/threading.py", line 1336, in invoke_excepthook
‎    ‎local_print("Exception in threading.excepthook:",‎
‎AttributeError‎: ‎'Stream' object has no attribute 'flush'‎
‎Exception ignored in sys.unraisablehook‎: ‎<built-in function unraisablehook>‎
‎AttributeError‎: ‎'Stream' object has no attribute 'flush'‎
‎Exception in thread ‎Thread-2 (between_callback)‎:
‎Traceback (most recent call last):
‎  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
‎    ‎self.run()‎
‎  File "/usr/local/lib/python3.10/threading.py", line 953, in run
‎    ‎self._target(*self._args, **self._kwargs)‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 729, in between_callback
‎    ‎loop.run_until_complete(start_bot(token, account_id))‎
‎  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
‎    ‎return future.result()‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 390, in start_bot
‎    ‎await MyClient().start(token)‎
‎  File "/home/pranav/Cosmoverse/Fun/Dank-Memer-Grinder-1.6.0-pre1/main.py", line 223, in __init__
‎    ‎super().__init__(command_prefix="-", self_bot=True)‎
‎TypeError‎: ‎BotBase.__init__() missing 1 required keyword-only argument: 'intents'‎
‎Exception in threading.excepthook:‎
‎Exception ignored in thread started by‎: ‎<bound method Thread._bootstrap of <Thread(Thread-2 (between_callback), started 140123425462016)>>‎
‎Traceback (most recent call last):
‎  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
‎    ‎self._bootstrap_inner()‎
‎  File "/usr/local/lib/python3.10/threading.py", line 1018, in _bootstrap_inner
‎    ‎self._invoke_excepthook(self)‎
‎  File "/usr/local/lib/python3.10/threading.py", line 1336, in invoke_excepthook
‎    ‎local_print("Exception in threading.excepthook:",‎
‎AttributeError‎: ‎'Stream' object has no attribute 'flush'‎
‎Exception ignored in sys.unraisablehook‎: ‎<built-in function unraisablehook>‎
‎AttributeError‎: ‎'Stream' object has no attribute 'flush'‎

**Screenshots**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/74840262/9e9d0798-e766-46f5-bfca-8480412a4f6a)

**OS:**
Linux amd64 running python unstable.

**Comment by aa552882** [comment]
you're using discord.py which is not made for userbots, either use a virtual env and install requirements or uninstall discord.py and install discord.py-self

**Comment by Tanuj27** [comment]
its the same with windows

**Comment by ray-deep** [comment]
bro me too

**Comment by wandeen** [comment]
same

**Comment by BridgeSenseDev** [comment]
Whats your discord.py-self version when doing pip list?
