### ISSUE TITLE
pls fix

### ISSUE THREAD

**Issue by suryansh00123** [BridgeSenseDev/Dank-Memer-Grinder#17]
=>pls fix the mini game like catching dragon, legendary fish, kraken, moleman (new from dig).
=>posting meme is now in a new format, pls change that
=>request to add /crime also in the bot
other than that it works like a charm, nice autobot.

**Comment by BridgeSenseDev** [comment]
Everything except for crime is fixed, crime will be added in the future

**Comment by BridgeSenseDev** [comment]
All done
