### ISSUE TITLE
Captcha Solver/ Moleman

### ISSUE THREAD

**Issue by bbribs** [BridgeSenseDev/Dank-Memer-Grinder#174]
The captcha solver doesn’t work, that’s the main suggestion or fix I would really be interested in. Also, the mole man box does work, it fails it’s most of the time, around 95%. But overall really good job on it.

**OS:**
Window

**Comment by bbribs** [comment]
Without the captcha solver, it makes you have to sit there and watch to make sure it doesn’t pop up rather than being able to afk.

**Comment by bbribs** [comment]
> which version are you using and is it running stable for you? for me 1.6 doesnt run for too long and it doesnt solve captchas do you have any solutions?

Well I don’t think it has captcha solver, I was just requesting it, mine runs fine, think I’m using the latest version. I run like 5 accounts and like every two hours or so one account will stop, so I just re input the channel ID and it resets

**Comment by BridgeSenseDev** [comment]
Captcha solver improved and moleman works fine, sometimes the clicks for moleman are delayed and theres nothing i can do about it
