### ISSUE TITLE
Adventure stuck

### ISSUE THREAD

**Issue by SparrowJG** [BridgeSenseDev/Dank-Memer-Grinder#175]
**Describe the bug**

When starting adventure, it indeed puts in the command: /adventure. However, it gets stuck on the tab: pick your items. It won’t click start. Though, when you click start yourself, it will proceed through the adventure right. 

Media:
https://cdn.discordapp.com/attachments/1125695813427937330/1134979035424890961/IMG_1203.png

it gets stuck on this screen unless clicked manually, rest works fine ^^

**Error**
there is no.

**OS:**
Windows

**Comment by ineeddankselfbots** [comment]
which version exactly are you using and how did you enable the auto adventure

**Comment by wandeen** [comment]
adventure still stuck and not working

**Comment by BridgeSenseDev** [comment]
Fixed in ceb4c95
