### ISSUE TITLE
Command /buy has moved to /shop buy

### ISSUE THREAD

**Issue by Kayull** [BridgeSenseDev/Dank-Memer-Grinder#21]
Just needs the autobuying fixing as command /buy is deprecated and is now /shop buy
![image](https://user-images.githubusercontent.com/45533484/201535053-e890beec-b728-4908-98bf-eb66c150c865.png)

**Comment by BridgeSenseDev** [comment]
Fixed in 17f33d38c04815c2cb1477558e07700eb7721acf, will make new release soon
