### ISSUE TITLE
Error when building: in.Captcha is undefined

### ISSUE THREAD

**Issue by QuartzWarrior** [BridgeSenseDev/Dank-Memer-Grinder#231]
**Describe the bug**
Clone the code ( git clone https://github.com/BridgeSenseDev/Dank-Memer-Grinder.git )
Run `go mod tidy`
Run `go build app.go`
Receive error.

**Error**
```bash
ubuntu@instance-20230620-1423:~/Dank-Memer-Grinder$ go build app.go 
# github.com/BridgeSenseDev/Dank-Memer-Grinder/instance
instance/instance.go:190:9: in.Captcha undefined (type *Instance has no field or method Captcha)
ubuntu@instance-20230620-1423:~/Dank-Memer-Grinder$
```
**Screenshots**
![image](https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/74436633/7b7347fc-c2e8-4706-927a-dc0598642c47)

**OS:**
Tried on both Linux arm64 and Linux amd64.

**Comment by StarEnthousiast** [comment]
The reason for this is that the captcha solver will not be made public, and instead there will be a exe, in which u can buy a api key to use as a captcha solver. It is up to bridge when he will release this so for the time being u won't be able to use it.

**Comment by QuartzWarrior** [comment]
> The reason for this is that the captcha solver will not be made public, and instead there will be a exe, in which u can buy a api key to use as a captcha solver. It is up to bridge when he will release this so for the time being u won't be able to use it.

Alright, I wanted to make contributions to this repo, but need to test/build it first. ig I'll make a temporary captcha solver in the meantime.
