### ISSUE TITLE
Can you please add automation of captchas?

### ISSUE THREAD

**Issue by 1010saf** [BridgeSenseDev/Dank-Memer-Grinder#24]
i meant like automation of captchas such as these:-
![image](https://user-images.githubusercontent.com/92152439/204014370-e4d5e5cd-e6b6-40ef-ac40-b87bcaf50bc3.png)

i don't know if this is possible, but if you can add this feature it will be really helpful!
ty for your time

**Comment by BridgeSenseDev** [comment]
> i meant like automation of captchas such as these:- ![image](https://user-images.githubusercontent.com/92152439/204014370-e4d5e5cd-e6b6-40ef-ac40-b87bcaf50bc3.png)
> 
> i don't know if this is possible, but if you can add this feature it will be really helpful! ty for your time

Have you gotten a captcha from using the bot? I have multiple accounts on with all commands active and ive never gotten a captcha

**Comment by 1010saf** [comment]
> > i meant like automation of captchas such as these:- ![image](https://user-images.githubusercontent.com/92152439/204014370-e4d5e5cd-e6b6-40ef-ac40-b87bcaf50bc3.png)
> > i don't know if this is possible, but if you can add this feature it will be really helpful! ty for your time
> 
> Have you gotten a captcha from using the bot? I have multiple accounts on with all commands active and ive never gotten a captcha

Catchas are really random... , it only appears like once a month or so..., 
I haven't gotten one while using the bot but i did get one the day i commented this post while playing normally 

Idk for sure what triggers the captcha
I was worried if this might pop up while auto grinding thats why i posted this...

**Comment by 1010saf** [comment]
> 

Also

**Comment by BridgeSenseDev** [comment]
Added in 7d7438db8693f6d48004401ee67aa41a4130e6c4
