### ISSUE TITLE
auto grind stops 

### ISSUE THREAD

**Issue by ineeddankselfbots** [BridgeSenseDev/Dank-Memer-Grinder#28]
auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5

**Comment by BridgeSenseDev** [comment]
> auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5

Are you closing your laptop or is it going into sleep automatically? Does it stop by itself when you are actively using your laptop and keeping it on?

**Comment by 1010saf** [comment]
> auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5

it happens to me too, but rarely...

in order to prevent retyping token,
 just start the autofarm with the zip file open and add the tokens and start the auto farm and quit the autofarm with the zip file open, then a msg will appear saying "some files were updated, do you wish to save it" or smthing like that, click save... nxt time you use the auto farm, u won't have to type in the token again.. as long as the previous token gets invalid..
 
 i hope this makes sense lol

**Comment by BridgeSenseDev** [comment]
> > auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5
> 
> it happens to me too, but rarely...
> 
> in order to prevent retyping token, just start the autofarm with the zip file open and add the tokens and start the auto farm and quit the autofarm with the zip file open, then a msg will appear saying "some files were updated, do you wish to save it" or smthing like that, click save... next time you use the auto farm, you won't have to type in the token again.. as long as the previous token gets invalid..
> 
> i hope this makes sense lol
> 
> i meant this message, just click yes ![image](https://user-images.githubusercontent.com/92152439/206193543-d7e08fe0-9de9-4806-8301-9f634cfecadb.png)

If you extract the .exe and config.json from inside the zip into another place in for example your desktop, just closing and reopening the .exe will reload the tokens. I also fixed a bug which caused it to crash rarely on the next release

**Comment by ineeddankselfbots** [comment]
> > auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5
> 
> Are you closing your laptop or is it going into sleep automatically? Does it stop by itself when you are actively using your laptop and keeping it on?

no i am not closing my laptop the auto farm automatically stops by itself after 1 or 2 hours while i actively use the laptop
is there a solution?? ;(

**Comment by ineeddankselfbots** [comment]
> > auto grind stops after 1 or 2 hours and after it gets stopped we cant enable it again i have to get the tokens again and its very depressing for me i already lost billions cuz of account got hacked please provide me a solution please my laptop is windows 10 hp i5
> 
> it happens to me too, but rarely...
> 
> in order to prevent retyping token, just start the autofarm with the zip file open and add the tokens and start the auto farm and quit the autofarm with the zip file open, then a msg will appear saying "some files were updated, do you wish to save it" or smthing like that, click save... next time you use the auto farm, you won't have to type in the token again.. as long as the previous token gets invalid..
> 
> i hope this makes sense lol
> 
> i meant this message, just click yes ![image](https://user-images.githubusercontent.com/92152439/206193543-d7e08fe0-9de9-4806-8301-9f634cfecadb.png)

oki ill try
