### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Sxvxgee** [BridgeSenseDev/Dank-Memer-Grinder#4]
Looks like a nice app but the code is cursed, its pre write based, outdated.

Also while im not saying you should stop working on this project, [darkend](https://darkend.tech) exists.

**Comment by Sxvxgee** [comment]
> > 💀 darkend
> 
> why are you everywhere

nolife github user

**Comment by BridgeSenseMC** [comment]
> Looks like a nice app but the code is cursed, its pre write based, outdated.
> 
> Also while im not saying you should stop working on this project, [darkend](https://darkend.tech) exists.

Is Darkend open source?

**Comment by DaNxCorp** [comment]
> > Looks like a nice app but the code is cursed, its pre write based, outdated.
> > Also while im not saying you should stop working on this project, [darkend](https://darkend.tech) exists.
> 
> Is Darkend open source?

It is, and he's the dev.

Darkend got discontinued 4 days ago BTW. Your script is great (although in my Windows 10 machine it crashes after a couple hours every time), I encourage you to keep it up.

**Comment by BridgeSenseMC** [comment]
> > > Looks like a nice app but the code is cursed, its pre write based, outdated.
> > > Also while im not saying you should stop working on this project, [darkend](https://darkend.tech) exists.
> > 
> > 
> > Is Darkend open source?
> 
> It is, and he's the dev.
> 
> Darkend got discontinued 4 days ago BTW. Your script is great (although in my Windows 10 machine it crashes after a couple hours every time), I encourage you to keep it up.

Oh thanks i didn't know, I will continue but i don't have much time to work on it because of school. I'll release an update soon which will hopefully fix all the bugs and add support for multiple accounts.
