### ISSUE TITLE
Found a bug within the MacOS version of the grinder...

### ISSUE THREAD

**Issue by aditeyapatakoti** [BridgeSenseDev/Dank-Memer-Grinder#45]
So basically if you run the bot on a MacOS and put in a channel id into the slot it like never works... I've tried public servers, a direct message with dank memer itself, and even private servers.  I suggest adding a server id slot since it's much more efficient and helps most bots a ton as my friend made a bot with slash commands and works that way.. Though he did code in a language called "go"

**Comment by BridgeSenseDev** [comment]
Fixed
