### ISSUE TITLE
Program not starting `stream` and `work`

### ISSUE THREAD

**Issue by tedzify** [BridgeSenseDev/Dank-Memer-Grinder#60]
For some reason, the program does not start the `stream` and `work` most of the time, having the user to manually start the `stream` and `work` commands. Afterwards, the program interacts with these commands normally but unable to start them again. I noticed this issue when Dank Memer keeps messaged me about ending the stream because I didn't interact with it for a long time. The same goes for the `work` command.

What I also noticed is that, if all other commands are started, `stream` and `work` (and probably others I couldn't observe) does not start. However, these two start only if they are the only one's enabled.

**Comment by red78massive1573** [comment]
`crime` also didn't work

**Comment by BridgeSenseDev** [comment]
Fixed in latest release
