### ISSUE TITLE
Suggestion: Adventure 

### ISSUE THREAD

**Issue by Tx-3011** [BridgeSenseDev/Dank-Memer-Grinder#66]
you could add adventure too as a seperate mode

some resources that might help you-
-the cooldown is 3 minutes per interaction

-All the possible questions and responses and outcomes 
https://docs.google.com/spreadsheets/d/14AC-mmYNMrcdDGxfG2Nv0OAwq-Pkth1SIJuW3ADSXYQ/edit#gid=1274532499

**Comment by red78massive1573** [comment]
> some resources that might help you- -the cooldown is 3 minutes per interaction

The new cooldown is after your adventure ended. there are no cooldowns between interactions now.
The new cooldown math is `number of interactions * 2 minutes`

**Comment by BridgeSenseDev** [comment]
Added
