### ISSUE TITLE
Suggestion: Run scratch every 3 hours

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#70]
Maybe you could add a function where the dank grinder will run the scratch command every 3 hours (sometimes there are huge multipliers in the scratch)

implementing it, is up to you

**Comment by red78massive1573** [comment]
And sometimes there are huge multipliers

**Comment by red78massive1573** [comment]
Things to note: local pc time could be too fast or too slow, you should find a way to get current time that is correct and make a delay before calling the scratch function.

**Comment by red78massive1573** [comment]
Things to note: local pc time could be too fast or too slow, you should find a way to get current time that is correct and make a delay before calling the scratch function.

**Comment by 21Z** [comment]
why mess up pc time just set it correct

**Comment by red78massive1573** [comment]
> why mess up pc time just set it correct

i said could. so its up to him to make the code

**Comment by BridgeSenseDev** [comment]
Added in #189
