### ISSUE TITLE
Suggestion: make streaming commands have options

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#71]
Make a option in the program that lets the user pick if they want to click `Run AD` or `Collect Donations`.

Maybe make a chance input like the trivia input but change a little.
ex:

`Run AD : <user input like the trivia input>`
`Read Chat : <user input like the trivia input>`
`Collect Donations : <user input like the trivia input>`

just make a check function that counts the total of chances and show an error when the total is more than 100. 

Picture ex
![image](https://user-images.githubusercontent.com/87458936/226597194-bc1f21a7-9153-4de1-82e0-6519cec3f635.png)
When total is more than 100:
![image](https://user-images.githubusercontent.com/87458936/226597787-041d4c3d-922c-4c6b-926c-338011bcfc82.png)

**Comment by BridgeSenseDev** [comment]
Added in 755978d942a9e79c26237a243bbaa29ccfa64929
