### ISSUE TITLE
When auto buying life safers, the program withdrawn too less money

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#72]
**Describe the bug**
The bot withdraws less money when it needed more

**Screenshots**
![image](https://user-images.githubusercontent.com/87458936/226614336-0ce695ab-2a17-46a5-b78f-0c536aa830da.png)

**OS:**
Windows

**Comment by red78massive1573** [comment]
i think you should change the calculation
because life savers are 200k each

**Comment by 1010saf** [comment]
> > i made a pull req for this., so wait for the dev to update ig., #73
> 
> By the way, you did great with the pull request

thanks :D

**Comment by BridgeSenseDev** [comment]
Fixed in #73 ty
