### ISSUE TITLE
Program keeps on clicking the wash button on the pet menu

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#74]
**Describe the bug**
I don't know how the program got it self stuck in a loop but it keeps on clicking wash button

**Screenshots**
![image](https://user-images.githubusercontent.com/87458936/226684603-b3d4b7fd-e1d4-411b-acbb-3940cf640bcf.png)

**OS:**
Windows

**Comment by BridgeSenseDev** [comment]
Next time if this happens screenshot the original pet menu before deleting it

**Comment by red78massive1573** [comment]
everytime i try to find the original message, it says message cannot be loaded and its alr to far up to find it. and i cant look out for the problem all the time. bcz i let the program run in the background while im doing something else. i am very sorry
