### ISSUE TITLE
suggestion: Update the trivia answers.

### ISSUE THREAD

**Issue by bartf-Emlek** [BridgeSenseDev/Dank-Memer-Grinder#77]
The trivia seems to be outdated and it always misses the right answers most of the time, maybe it's time to update it or **add something that automatically logs the correct answers to the question then add it to the list of trivia answers**, kinda like the one on darkend.

**Comment by red78massive1573** [comment]
have you change the correct trivia chance to 100?
![image](https://user-images.githubusercontent.com/87458936/227404479-81f54cee-6528-4af5-bb04-b2fe00dd4742.png)

**Comment by red78massive1573** [comment]
mine is 90% chance, you can make it 100%
just change it on the settings menu

**Comment by red78massive1573** [comment]
this is implemented to make sure that dank memer doesn't get suspicious of you

**Comment by bartf-Emlek** [comment]
> have you change the correct trivia chance to 100? ![image](https://user-images.githubusercontent.com/87458936/227404479-81f54cee-6528-4af5-bb04-b2fe00dd4742.png)

**Comment by bartf-Emlek** [comment]
I've always set it on max (100), but still there's a lot of incorrect answers :/

**Comment by BridgeSenseDev** [comment]
Fixed in 7f4ea8f and e1dcec3
