### ISSUE TITLE
Pet command only interacts on 1st pet

### ISSUE THREAD

**Issue by bartf-Emlek** [BridgeSenseDev/Dank-Memer-Grinder#78]
The pet command doesn't seem to work properly, or I just misunderstood it??. It does what it supposed to do on my first pet; feed, wash, and play with my pet, but after that, I'm expecting it to switch to my other pets to do the same interactions on them. But it didn't, I manually switch it but it doesn't get fed and washed, but it did able to play with my pet when I press the play button. The play and walk button seems to be missing too, hopefully it gets added later.

**Comment by red78massive1573** [comment]
the program only expect the user to only have 1 pets

**Comment by BridgeSenseDev** [comment]
Fixed in 6d3d96c
