### ISSUE TITLE
Work shift command does not work on emoji sometimes

### ISSUE THREAD

**Issue by 21Z** [BridgeSenseDev/Dank-Memer-Grinder#82]
**Describe the bug**
A clear and concise description of what the bug is and steps to reproduce.
Bug 1: Work shift does not click correct emoji when dank memer asked to click the correct emoji.
Bug 2: Program runs other commands while a command is going on, happens with work shift, postmemes (gives error: An ongoing command is running)
Bug 3: Program clicks buttons/works in commands of other users.

**Error**
Click on the home tab and send the full error if there is one.

**Screenshots**
![image](https://user-images.githubusercontent.com/69188068/227827857-bd8fc95c-c0b0-4e70-9c3e-56d355a7a081.png)

**OS:**
Windows

**Comment by red78massive1573** [comment]
are you using the program in a public channel?

**Comment by BridgeSenseDev** [comment]
Fixed in a676bfc
