### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#84]
**Describe the bug**
After updating and running the program, it will run a few commands in discord and just stop running and clicking buttons.

**Error**
‎‎Unhandled exception in internal background task 'commands'.‎
‎Traceback (most recent call last):
‎‎  File "discord\ext\tasks\__init__.py", line 241, in _loop
‎‎  File "C:\Users\owenh\AppData\Local\Temp\_MEI135962\cogs\commands.py", line 45, in commands
    await self.bot.send(self.bot.commands_dict[command])
‎‎  File "main.py", line 221, in send
‎‎  File "discord\commands.py", line 606, in __call__
‎‎TypeError: Cannot use a group

**Screenshot**
![image](https://user-images.githubusercontent.com/87458936/229085548-84d8d39c-6db6-4ac8-8870-d971b118ba6d.png)

**OS:**
Windows

**Comment by red78massive1573** [comment]
i needed to redownload the older version to use the program again

**Comment by BridgeSenseDev** [comment]
Fixed
