### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by AnonymousFxz** [BridgeSenseDev/Dank-Memer-Grinder#87]
My antivirus keeps going off and thinks the new file is a virus win64:dropperxgen

**Comment by skifli** [comment]
@AnonymousFxz It is not a virus, but if you don't trust the compiled binaries then run it from source. My AV (Kaspersky) doesn'tt flag it, but different AVs may have different results. It is common for compiled Python programs to be flagged as viruses.

**Comment by AnonymousFxz** [comment]
ive been using this a lot and i trust it lol.
