### ISSUE TITLE
Idea?

### ISSUE THREAD

**Issue by AnonymousFxz** [BridgeSenseDev/Dank-Memer-Grinder#90]
I've noticed whenever I open the program it makes a new folder in \AppData\Local\Temp and it kinda gets annoying is there a way to make all the code go in the folder the .exe was opened in?

**Comment by BridgeSenseDev** [comment]
Its a temp folder for a reason why is it annoying

**Comment by skifli** [comment]
No, the exe was compiled using one-file mode, meaning it needs to make a separate directory to extract the code into.

**Comment by skifli** [comment]
No, the exe was compiled using one-file mode, meaning it needs to make a separate directory to extract the code into. A fix would be to compile it in one-dir mode but then the folder you downloaded the executable into will have 100s of files (DLLs, code, etc), making it harder to find the actual executable when you want to run it.

**Comment by BridgeSenseDev** [comment]
^^

**Comment by IncognitoTGT** [comment]
Also the project is open source so you can edit the code and recompile it so that it goes to another directory, such as `~/dankcache` or something.

**Comment by skifli** [comment]
> Also the project is open source so you can edit the code and recompile it so that it goes to another directory, such as `~/dankcache` or something.

No you can't, as the directory is not linked to the program. It is linked to the compiler used, which is PyInstaller, and so you would have to find a way to tell PyInstaller to use a different directory.
