### ISSUE TITLE
Pets percentage str to int error

### ISSUE THREAD

**Issue by red78massive1573** [BridgeSenseDev/Dank-Memer-Grinder#95]
**Describe the bug**
I just let the program ran and when im back the log is already filled with the error

**Error**
```
‎‎Ignoring exception in on_message‎
‎Traceback (most recent call last):
‎‎  File "discord\client.py", line 417, in _run_event
‎‎  File "C:\Users\owenh\AppData\Local\Temp\_MEI69282\cogs\pets.py", line 29, in on_message
    percentage = int(
                 ^^^^
‎‎ValueError: invalid literal for int() with base 10: '10/10'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/87458936/229580684-b5187a37-92ac-4f26-80e7-ca1f5bd7426d.png)
![image](https://user-images.githubusercontent.com/87458936/229580780-aa3b7cdf-b147-4c3a-b512-5126e9d8f6dd.png)

**OS:**
Windows

**Comment by BridgeSenseDev** [comment]
Should be fixed in 19f257d
