### ISSUE TITLE
New Cooldowns Update

### ISSUE THREAD

**Issue by MysteryDealer** [BridgeSenseDev/Dank-Memer-Grinder#97]
New Update, New Cooldown
[https://dankmemer.lol/changelog](url)
![image](https://user-images.githubusercontent.com/88203643/230549643-a2a4b395-2320-4a5c-829e-da66c0f67c44.png)

**Comment by ineeddankselfbots** [comment]
you can configure the cooldowns youself just click the numbers and edit how many seconds

**Comment by MysteryDealer** [comment]
> you can configure the cooldowns youself just click the numbers and edit how many seconds

i meant to set that as default ones

**Comment by Kathund** [comment]
=> New Update, New Cooldown [https://dankmemer.lol/changelog](url) ![image](https://user-images.githubusercontent.com/88203643/230549643-a2a4b395-2320-4a5c-829e-da66c0f67c44.png)

Do you know what al the new cooldowns are coz i will make a pull request to change them. This will save time and not force me to test every command

**Comment by MysteryDealer** [comment]
> => New Update, New Cooldown [https://dankmemer.lol/changelog](url) ![image](https://user-images.githubusercontent.com/88203643/230549643-a2a4b395-2320-4a5c-829e-da66c0f67c44.png)
> 
> Do you know what al the new cooldowns are coz i will make a pull request to change them. This will save time and not force me to test every command

these are the cooldowns, the ones I have set and took screenshot of

**Comment by Kathund** [comment]
> > => New Update, New Cooldown [https://dankmemer.lol/changelog](url) ![image](https://user-images.githubusercontent.com/88203643/230549643-a2a4b395-2320-4a5c-829e-da66c0f67c44.png)
> > Do you know what al the new cooldowns are coz i will make a pull request to change them. This will save time and not force me to test every command
> 
> these are the cooldowns, the ones I have set and took screenshot of

AH IGHT WHEN I FIND THE TIME I WILL
