### ISSUE TITLE
script stops within 5 mins of turning it on

### ISSUE THREAD

**Issue by ineeddankselfbots** [BridgeSenseDev/Dank-Memer-Grinder#98]
os: windows
  
  version 1.5.2
  auto grind grind stops after 5 mins from turning it on or just stop running cmds within an hour pls fix this 
  im wasting valuable time pls comsider this

**Comment by red78massive1573** [comment]
downgrade your version to 1.5.0
Pros:
still working

Cons:
autobuy is broken
